### ISSUE TITLE
SyntaxError on import

### ISSUE THREAD

**Issue by rasmi** [pysal/pysal#1008]
- Platform information:
`('posix', 'darwin')`
- Python version: 
`2.7.13`
- SciPy version:
`0.19.1`
- NumPy version:
`1.13.3`
---
When I try to import pysal:
```
import pysal
```
I get the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "python2env/lib/python2.7/site-packages/pysal/__init__.py", line 40, in <module>
    import pysal.cg
  File "python2env/lib/python2.7/site-packages/pysal/cg/__init__.py", line 4, in <module>
    from .shapes import *
  File "python2env/lib/python2.7/site-packages/pysal/cg/shapes.py", line 1972, in <module>
    from . import standalone  # moving this to top breaks unit tests !
  File "python2env/lib/python2.7/site-packages/pysal/cg/standalone.py", line 15, in <module>
    from pysal.common import *
  File "python2env/lib/python2.7/site-packages/pysal/common.py", line 22, in <module>
    from pysal.core.FileIO import FileIO as popen
  File "python2env/lib/python2.7/site-packages/pysal/core/__init__.py", line 1, in <module>
    from . import FileIO
  File "python2env/lib/python2.7/site-packages/pysal/core/FileIO.py", line 37
    class FileIO(object, metaclass=FileIO_MetaCls):  # should be a type?
                                  ^
SyntaxError: invalid syntax
```
I do not get this issue with Python 3. Any help would be appreciated!

**Comment by Brideau** [comment]
Any update on this? Having the same issue.

**Comment by rgommers** [comment]
This issue can be closed, ` class FileIO(object, metaclass=FileIO_MetaCls):` has been changed to  `class FileIO(object):` in master, and CI is passing on py27

**Comment by mykolakozyr** [comment]
This issue still exists while installing using pip

**Comment by sjsrey** [comment]
@mykolakozyr it is fixed in master. The fix won't be on pip until the next release.
