### ISSUE TITLE
Missing example files in libpysal

### ISSUE THREAD

**Issue by sjsrey** [pysal/pysal#1045]
======================================================================
ERROR: test_fuzzy_contiguity (pysal.lib.libpysal.weights.tests.test_util.Testutil)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/serge/Dropbox/p/pysal/src/meta/pysal/pysal/lib/libpysal/weights/tests/test_util.py", line 243, in test_fuzzy_contiguity
    rs = lps.get_path('map_RS_BR.shp')
  File "/home/serge/Dropbox/p/pysal/src/meta/pysal/pysal/lib/examples/__init__.py", line 35, in get_path
    raise KeyError(example_name + ' not found in PySAL built-in examples.')
KeyError: 'map_RS_BR.shp not found in PySAL built-in examples.'

```

**Comment by sjsrey** [comment]
examples live here: https://github.com/pysal/pysal/tree/master/pysal/examples

**Comment by sjsrey** [comment]
[rio.zip](https://github.com/pysal/pysal/files/2195788/rio.zip)
