### ISSUE TITLE
current TravisCI build failures (late May 2019)

### ISSUE THREAD

**Issue by jGaboardi** [pysal/pysal#1100]
96 of the 97 current [TravisCI build failures](https://travis-ci.org/pysal/pysal/jobs/537084137) ([beginning here](https://travis-ci.org/pysal/pysal/builds/534896277)) occur in `spreg` appear to happen at [`scipy.stats.pearsonr`](https://travis-ci.org/pysal/pysal/jobs/537084137#L4892-L4900), which may be related to the recent `scipy 1.2.1` to `1.3.0` (pysal/libpysal#122, pysal/libpysal#154).
```
File "/home/travis/build/pysal/pysal/pysal/model/spreg/diagnostics_tsls.py", line 217, in pr2_aspatial
    pr = pearsonr(y, predy)[0]
  File "/home/travis/build/pysal/pysal/miniconda/envs/test-env/lib/python3.6/site-packages/scipy/stats/stats.py", line 3410, in pearsonr
    xmean = x.mean(dtype=dtype)
  File "/home/travis/build/pysal/pysal/miniconda/envs/test-env/lib/python3.6/site-packages/numpy/core/_methods.py", line 75, in _mean
    ret = umr_sum(arr, axis, dtype, out, keepdims)
TypeError: No loop matching the specified signature and casting
was found for ufunc add
```

The remaining failure occurs in [`spvcm`](https://travis-ci.org/pysal/pysal/jobs/537084137#L6930-L6946)

```
======================================================================
ERROR: test_values (pysal.model.spvcm.tests.test_diagnostics.Test_Effective_Size)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/pysal/pysal/pysal/model/spvcm/tests/test_diagnostics.py", line 98, in test_values
    single_size = effective_size(trace=self.single_trace, use_R = False, varnames='Tau2')
  File "/home/travis/build/pysal/pysal/pysal/model/spvcm/diagnostics.py", line 434, in effective_size
    stats = trace.map(_effective_size, use_R=use_R)
  File "/home/travis/build/pysal/pysal/pysal/model/spvcm/abstracts.py", line 405, in map
    stats = [func(datum, **func_args) for datum in data]
  File "/home/travis/build/pysal/pysal/pysal/model/spvcm/abstracts.py", line 405, in <listcomp>
    stats = [func(datum, **func_args) for datum in data]
  File "/home/travis/build/pysal/pysal/pysal/model/spvcm/diagnostics.py", line 459, in _effective_size
    spec = _spectrum0_ar(x)
  File "/home/travis/build/pysal/pysal/pysal/model/spvcm/diagnostics.py", line 379, in _spectrum0_ar
    raise ImportError('Statsmodels is required to use the AR(0) '
ImportError: Statsmodels is required to use the AR(0)  spectral density estimate of the variance.
```

**Comment by jGaboardi** [comment]
@sjsrey @weikang9009

**Comment by sjsrey** [comment]
I think the failures for spreg and spvcm within the meta package are due to us bumping up to 3.6 and 3.7 and dropping 3.5 - this evidently bumps scipy from 1.2.1 to 1.3.0.

as standalones, spreg and [spvcm](https://travis-ci.org/pysal/spvcm/jobs/537082943) integration tests are passing, but that is because they are using scipy 1.2.1. My bet is when they bump up to 1.3.0 we will see the errors that we are encountering here in the meta-package.

We should fix these upstream rather than here, I think.

**Comment by jGaboardi** [comment]
pysal/spvcm#8
