### ISSUE TITLE
Bug in setup.py

### ISSUE THREAD

**Issue by sjsrey** [pysal/pysal#564]
Users reported a fatal bug when using pip install pysal and it can be replicated locally:

```
mbr:~ serge$ pip install -U pysal
Downloading/unpacking pysal from https://pypi.python.org/packages/source/P/PySAL/PySAL-1.9.0.tar.gz#md5=06f1696560d39218bf5a80f0a9bdf060
  Downloading PySAL-1.9.0.tar.gz (10.8MB): 10.8MB downloaded
  Running setup.py (path:/private/var/folders/7y/72fwgkyj7z30v_vrd7w1fl380000gn/T/pip_build_serge/pysal/setup.py) egg_info for package pysal
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/private/var/folders/7y/72fwgkyj7z30v_vrd7w1fl380000gn/T/pip_build_serge/pysal/setup.py", line 18, in <module>
        with open('README.md') as file:
    IOError: [Errno 2] No such file or directory: 'README.md'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/private/var/folders/7y/72fwgkyj7z30v_vrd7w1fl380000gn/T/pip_build_serge/pysal/setup.py", line 18, in <module>

    with open('README.md') as file:

IOError: [Errno 2] No such file or directory: 'README.md'
```

**Comment by sjsrey** [comment]
If I point pip to the tag on git hub I don't encounter this error:

      pysal:~ serge$ pip install -U https://github.com/pysal/pysal/archive/v1.9.tar.gz

I'm wondering if something went south in the `pip setup.py  sdist upload`

Last night I deleted the pypi release for 1.9 and this morning rebuilt it and uploaded. However, although 1.9 is listed when using `pip install -U pysal` on clean virtual machine I'm getting 1.8 not 1.9.

Thinking that removing the 1.9 and then pushing up a release with the same number might have pypi in a weird state (i.e., getting 1.8 when it shows 1.9 as latest). Thinking of doing a release 1.9.1 to fix. 

Any thoughts?

**Comment by sjsrey** [comment]
the file built with `python setup.py sdist` which is PySAL-1.9.0.tar.gz is missing README.md

**Comment by sjsrey** [comment]
Tested 1.9.1 upload on pypi and all is well. Closing
