### ISSUE TITLE
ImportError: No module named scipy.spatial

### ISSUE THREAD

**Issue by LreeLenn** [pysal/pysal#801]
>>> import pysal

Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    import pysal
  File "E:\Python27\ArcGISx6410.2\lib\site-packages\pysal\__init__.py", line 40, in <module>
    import pysal.cg
  File "E:\Python27\ArcGISx6410.2\lib\site-packages\pysal\cg\__init__.py", line 4, in <module>
    from shapes import *
  File "E:\Python27\ArcGISx6410.2\lib\site-packages\pysal\cg\shapes.py", line 12, in <module>
    from sphere import arcdist
  File "E:\Python27\ArcGISx6410.2\lib\site-packages\pysal\cg\sphere.py", line 16, in <module>
    import scipy.spatial
ImportError: No module named scipy.spatial
>>>

**Comment by sjsrey** [comment]
Can you try to directly import scipy.spatial?

**Comment by LreeLenn** [comment]
Thanks you for your reply.
I have not installed the module "scipy" before.
