### ISSUE TITLE
Undocumented hard dependency on six 

### ISSUE THREAD

**Issue by sjsrey** [pysal/pysal#804]
In a pure conda environment with only python 2 or 3 plus scipy we have a missing dependency:

```
Python 3.5.1 |Continuum Analytics, Inc.| (default, Dec  7 2015, 11:16:01) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pysal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/serge/anaconda2/envs/pysal-1.11.3/lib/python3.5/site-packages/pysal/__init__.py", line 51, in <module>
    from pysal.esda.moran import Moran, Moran_BV, Moran_BV_matrix, Moran_Local, Moran_Local_BV
  File "/home/serge/anaconda2/envs/pysal-1.11.3/lib/python3.5/site-packages/pysal/esda/__init__.py", line 7, in <module>
    from . import moran
  File "/home/serge/anaconda2/envs/pysal-1.11.3/lib/python3.5/site-packages/pysal/esda/moran.py", line 7, in <module>
    from pysal.weights.spatial_lag import lag_spatial as slag
  File "/home/serge/anaconda2/envs/pysal-1.11.3/lib/python3.5/site-packages/pysal/weights/__init__.py", line 11, in <module>
    from .spatial_lag import *
  File "/home/serge/anaconda2/envs/pysal-1.11.3/lib/python3.5/site-packages/pysal/weights/spatial_lag.py", line 8, in <module>
    from six import iteritems as diter
ImportError: No module named 'six'
>>> 
```

Installing six fixes this:

```
(pysal-1.11.3)~/tmp » pip install six
Collecting six
  Downloading six-1.10.0-py2.py3-none-any.whl
Installing collected packages: six
Successfully installed six-1.10.0
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(pysal-1.11.3)~/tmp » python
Python 3.5.1 |Continuum Analytics, Inc.| (default, Dec  7 2015, 11:16:01) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pysal
Pandas adapters not loaded
>>> 
```

**Comment by sjsrey** [comment]
Since [six](https://pypi.python.org/pypi/six) is a single file with a compatible license, one solution is for us to include it rather than have it as a hard dependency.

**Comment by sjsrey** [comment]
Fixed with https://github.com/pysal/pysal/pull/806/commits/37b78be3455bbf87cf9737dccb291dd03edb0364
