### ISSUE TITLE
Nose tests fail for python 3 in Windows

### ISSUE THREAD

**Issue by karldw** [pysal/pysal#956]
Nose tests fail (none of them are run) on Python 3 and Windows. I'm getting the error `ModuleNotFoundError: No module named 'shapes'` from the command `from shapes import *` in `pysal\pysal\cg\__init__.py`.
I think this is an error with absolute/relative imports.

- Platform information: win32 (Windows 10)
- Python version: 3.6.1
- SciPy version: 0.19.1
- NumPy version: 1.13.1

The nose tests run on the same platform under Python 2.7.13.
The issue is the same under git cmd and git bash.

<details>

```
(py3) C:\Users\karldw\Desktop\pysal>nosetests pysal
E
======================================================================
ERROR: Failure: ModuleNotFoundError (No module named 'shapes')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\karldw\AppData\Local\Continuum\Miniconda3\envs\py3\lib\site-packages\nose\failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "C:\Users\karldw\AppData\Local\Continuum\Miniconda3\envs\py3\lib\site-packages\nose\loader.py", line 417, in loadTestsFromName
    addr.filename, addr.module)
  File "C:\Users\karldw\AppData\Local\Continuum\Miniconda3\envs\py3\lib\site-packages\nose\importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "C:\Users\karldw\AppData\Local\Continuum\Miniconda3\envs\py3\lib\site-packages\nose\importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "C:\Users\karldw\AppData\Local\Continuum\Miniconda3\envs\py3\lib\imp.py", line 244, in load_module
    return load_package(name, filename)
  File "C:\Users\karldw\AppData\Local\Continuum\Miniconda3\envs\py3\lib\imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 675, in _load
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "C:\Users\karldw\Desktop\pysal\pysal\__init__.py", line 40, in <module>
    import pysal.cg
  File "C:\Users\karldw\Desktop\pysal\pysal\cg\__init__.py", line 4, in <module>
    from shapes import *
ModuleNotFoundError: No module named 'shapes'

----------------------------------------------------------------------
Ran 1 test in 0.002s

FAILED (errors=1)
```

</details>

Ref: #151

**Comment by ljwolf** [comment]
The source code of PySAL is currently Python2 only. The error you're seeing is due to trying to import the code without running our setup script first. 

We've just pushed a source version in python 3 to the `dev3` branch yesterday. 

For running the tests, try running `2to3 -nw pysal/` in the root directory before running the test suite.
