### ISSUE TITLE
Passing Arc_KDTree to partial wrapper changes it to scipy based cKDTree

### ISSUE THREAD

**Issue by Jeeva-Ganesan** [pysal/pysal#986]
Hello,

I am constructing my tree beforehand and passing it with my data to do further processing, however, when i pass it to partial function from functools, tree type is changing to scipy based one, due to which i am getting the error - search for 2 dimensional point in 3 dimensional space. 

```
def construct_geopoints(s):
    property_geopoints = [tuple(x) for x in s[['longitude','latitude']].to_records(index=False)]
    tree = KDTree(property_geopoints, distance_metric='Arc', radius=pysal.cg.RADIUS_EARTH_KM)
    return tree

tree = construct_geopoints(masterdata)

print tree
<pysal.cg.kdtree.Arc_KDTree object at 0x113d744b0>

def myfunc(d,e,tree,mydict,s):
      print tree

<scipy.spatial.ckdtree.cKDTree object at 0x113e8b6d0>

out = mypool.imap(partial(myfunc,d,e,tree,mydict), (group for name,group in df_gp))


```
- Platform information:
```python
>>> import os; print(os.name, os.sys.platform)
 ('posix', 'linux2')
- Python version: 
```python
>>> import sys; print(sys.version)
2.7.13 |Anaconda custom (64-bit)| (default, Dec 20 2016, 23:09:15) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
- SciPy version:
python
>>> import scipy; print(scipy.__version__)
0.19.0
- NumPy version:
```python
>>> import numpy; print(numpy.__version__)
1.12.1

**Comment by ljwolf** [comment]
I can't replicate this straightforward when I do what you've shown:
```python
import pysal as ps
import numpy as np
np.random.seed(312211)
lngs = np.random.uniform(-180,180,(100,1))
lats = np.random.uniform(-90,90,(100,1))
coords = np.hstack((lngs,lats))

tree = ps.cg.KDTree(coords, distance_metric='Arc', radius=ps.cg.RADIUS_EARTH_KM)

def test_partial(a,b,tree,d,final):
    print(tree)
    return type(tree)

from functools import partial

partial(test_partial, 1, 2, tree,d)(3)
<pysal.cg.kdtree.Arc_KDTree object at 0x7f08e30efbb0>
pysal.cg.kdtree.Arc_KDTree
```
The type instability isn't with the partial application, so far as I can tell. I **can** replicate once I recalled that multiprocess uses pickle under the hood to pass stuff around:
```python
import pickle as pkl
pkl.loads(pkl.dumps(tree))
<scipy.spatial.ckdtree.cKDTree at 0x7f08e3040d50>
```
So, this likely boils down to the fact that our `Arc_KDTree` does not define its own `__reduce__` method.

**Comment by ljwolf** [comment]
We'll have to look into how to build that reduce method correctly. I'm not sure off the top of my head, & I've never written code that works with this end of the pickling systme.

**Comment by rasmi** [comment]
I am getting the same issue. Specifically,

```
from __future__ import print_function
import pickle
import pysal as ps
import numpy as np
from scipy.spatial import cKDTree

np.random.seed(42)
lngs = np.random.uniform(-180, 180, (100, 1))
lats = np.random.uniform(-90, 90, (100, 1))
coords = np.hstack((lngs, lats))

tree = ps.cg.KDTree(coords, distance_metric='Arc', radius=ps.cg.RADIUS_EARTH_KM)
# This works if we use the default scipy cKDTree.
#tree = cKDTree(coords)

print(tree.query((90, 0), k=2))

pickle.dump(tree,open('tree.p','wb'))
tree = pickle.load(open('tree.p', 'rb'))
print(tree.query((90, 0), k=2))
```
Gives the error:
```
Traceback (most recent call last):
  File "test.py", line 19, in <module>
    print(tree.query((90, 0), k=2))
  File "scipy/spatial/ckdtree.pyx", line 731, in scipy.spatial.ckdtree.cKDTree.query (scipy/spatial/ckdtree.cxx:7657)
ValueError: x must consist of vectors of length 3 but has shape (2,)
```

This is happening  because the nested class is not being pickled properly (see [here](https://stackoverflow.com/a/11493777)), so `query` is not performing the [`self._toXYZ(x)` call found in `Arc_KDTree`](https://github.com/pysal/pysal/blob/8a487c10668496c68fd7f834c369c50b1506535c/pysal/cg/kdtree.py#L159). 

You can work around it by applying the necessary transformations (convert `(lng,lat)` to XYZ, and convert linear distance to arc distance) after loading the pickled object:
```
import pysal.cg.sphere as sphere

tree = pickle.load(open('tree.p', 'rb'))
d, i = tree.query(sphere.toXYZ((90, 0)), k=2)
print((np.array([sphere.linear2arcdist(dx, sphere.RADIUS_EARTH_KM) for dx in d]), i))
```
